import "@humyn/ui"; // UI design system styles
import "./global.scss"; // App-specific global styles

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "test2",
  description: "Generated by Humyn CLI",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
