import "./global.scss";
import "@humyn/ui/dist/styles.css";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "__APP_NAME__",
  description: "Generated by Humyn CLI",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="humyn-bd">{children}</body>
    </html>
  );
}
